### ISSUE TITLE
Miss sound

### ISSUE THREAD

**Issue by Proulxs** [Kylemc1413/HitSoundChanger#1]
It looks as if as soon as you place an audio file the Miss sound stop working. You can add a HitSound and BadHitSound (if you cut in wrong direction or with wrong saber) but the Miss sound (if you do not hit it) just stop working completly and you end up with silence...

I've tried using miss.ogg and missSound.ogg without success because well I have not a clue what am I doing. So I looked in plugin.cs and there are no mentions of miss but no mention of taking off the game's sound off either so I'm not sure what to do...

**Comment by Kylemc1413** [comment]
Probably Because there is no miss sound in the game, at all

**Comment by seansaad** [comment]
wheres the insructions

**Comment by Kylemc1413** [comment]
Same place as the mod download in bsmg discord

**Comment by sovietspaceship** [comment]
I'm having the same issue. The problem is *not* that the mod does not change miss sounds (it's the same sound as bad cut, so same sound file), but that when set to non-default sounds misses produce no sounds whatsoever. This is certainly not intended

**Comment by Kylemc1413** [comment]
As I said previously, there is literally no miss sound in the game. If you miss a note there is no sound that plays, if you get a near miss on a note the hitsound will sometimes play due to how the game prepares hitsounda, but that is all

**Comment by sovietspaceship** [comment]
Correct, there's no miss sound. I've done some testing and it seems the base game plays the hit sound with a low and decreasing volume, which may be perceived as a "miss sound", while changing sounds using the mod does not reduce the volume and plays it a full volume, not to mention being more noticeable depending on the sound set.

**Comment by Kylemc1413** [comment]
All the mod does is replace the sound clips used for the hitsounds, the randomized pitch and every other aspect of how hitsounds are played is unchanged. This issue was closed for a reason

**Comment by sovietspaceship** [comment]
Since you confirm the mod maintains all the aspects of how the hit sound works, it must be the custom hit sound itself that is confusingly high volume and maintains a volume that is too high on miss as well and not something the mod can be patched to fix. I'll try changing the sound file and see if that improves, otherwise I'll try a different sound set or switch to the default when playing without ui. Cheers!
