### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Atramentius** [Kylemc1413/HitSoundChanger#2]
I'm sorry but I don't know what to do with those files. I have downloaded the master hit sound changer zip file and the hitsoundchanger.dll but I don't know where to put them. I also didn't find the UserData/HitSoundChanger Folder you were pointing on in the Readme. 
Is there any Installation guide I did miss?

**Comment by Kylemc1413** [comment]
Follow the instructions on the post in #pc-mods in the beat saber modding group

**Comment by Atramentius** [comment]
well thanks for nothing I guess. The Discord post contains the excat same information as the readme.    (—__—)

**Comment by Atramentius** [comment]
![Screenshot_20200206_075845_com discord](https://user-images.githubusercontent.com/60711987/73913145-8fadc800-48b6-11ea-82fd-828013a2b01c.jpg)

**Comment by Kylemc1413** [comment]
If you need help installing mods, perhaps go to the #pc-help channel in the discord
