### ISSUE TITLE
how do i get the dll for this using the master folder?

### ISSUE THREAD

**Issue by chilleryzz** [Kylemc1413/HitSoundChanger#7]
same as title

**Comment by chilleryzz** [comment]
and for my own sake don't put a discord thing AAAAAAA (1.13.2)

**Comment by Kylemc1413** [comment]
Compiling the mod using Visual Studio, if you want to download an actual mod release you would have to get it from the pc-mods channel in the Beat Saber Modding Group discord

**Comment by chilleryzz** [comment]
ok ty
