### ISSUE TITLE
hitsounds will not show up in hitsound menu

### ISSUE THREAD

**Issue by coulterminer** [Kylemc1413/HitSoundChanger#8]
I've dropped the `HitSound.ogg` `BadHitSound.ogg` into the `UserData\HitSoundChanger` folder. Absolutely nothing happens, am I doing something wrong, or is it the plugin

**Comment by Kylemc1413** [comment]
Audio files don't go directly in the HitsoundChanger folder, so the former, read the instructions with the mod post in the beat saber modding group pc-mods channel

**Comment by coulterminer** [comment]
I did, I put it in the user data folder as instructed
